// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeZsqK-q7qM2IoePkSwD5G80EPcFHw34',
    appId: '1:491094407192:web:74f8cee1ff1b42e7502b6d',
    messagingSenderId: '491094407192',
    projectId: 'fooddelivery-74fe1',
    authDomain: 'fooddelivery-74fe1.firebaseapp.com',
    storageBucket: 'fooddelivery-74fe1.appspot.com',
    measurementId: 'G-2ST7V7EB2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxZK6xcKQnxuSAvRVQi7sDwnVHgf84HY',
    appId: '1:491094407192:android:e7bd75866917c7c9502b6d',
    messagingSenderId: '491094407192',
    projectId: 'fooddelivery-74fe1',
    storageBucket: 'fooddelivery-74fe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTLe0ecvXZGhweR1N8K-lTlpy6QgUOYE',
    appId: '1:491094407192:ios:a9060e042dc35917502b6d',
    messagingSenderId: '491094407192',
    projectId: 'fooddelivery-74fe1',
    storageBucket: 'fooddelivery-74fe1.appspot.com',
    iosBundleId: 'com.example.fullFoodDeliveryAppWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUTLe0ecvXZGhweR1N8K-lTlpy6QgUOYE',
    appId: '1:491094407192:ios:a9060e042dc35917502b6d',
    messagingSenderId: '491094407192',
    projectId: 'fooddelivery-74fe1',
    storageBucket: 'fooddelivery-74fe1.appspot.com',
    iosBundleId: 'com.example.fullFoodDeliveryAppWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALeZsqK-q7qM2IoePkSwD5G80EPcFHw34',
    appId: '1:491094407192:web:c25c96ee36ced9de502b6d',
    messagingSenderId: '491094407192',
    projectId: 'fooddelivery-74fe1',
    authDomain: 'fooddelivery-74fe1.firebaseapp.com',
    storageBucket: 'fooddelivery-74fe1.appspot.com',
    measurementId: 'G-REPKMX21DL',
  );
}
